/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cnfmtbvbmkxdvbbpdtle"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZm10YnZibWt4ZHZiYnBkdGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3OTk5MDksImV4cCI6MjA4NjM3NTkwOX0.yuRTlk8i7t7dIAOiI7-9eyyMx8L1yvy4HD-g0j_gD7w"